# me_soe 分区

# check support parttion
SHOW VARIABLES LIKE '%partion%'

# chechk mysql version
SELECT @@version

# copy table structure don't have data
CREATE TABLE IF NOT EXISTS  cisp_platform.me_soe_copy2018_12_25 (LIKE cisp_platform.me_soe)
DROP TABLE me_soe_copy2018_12_25
# check create table
SHOW CREATE TABLE cisp_platform.me_soe;

# create table statement
SHOW CREATE TABLE cisp_platform.me_soe;

# get count
SELECT COUNT(*) FROM cisp_platform.me_soe
SELECT * FROM cisp_platform.me_soe


# create store procedure to generate partition statement

DROP PROCEDURE IF EXISTS base.sp_CreateParttionTable;
DELIMITER //
CREATE PROCEDURE base.sp_CreateParttionTable(createtable MEDIUMTEXT,parttitionnum MEDIUMINT)
BEGIN
loopout:BEGIN
	# get parttions detail
	# select * from information_schema.PARTITIONS where table_schema=schema() and table_name='me_soe'
	
	# chech argument is valid
	DECLARE partNum MEDIUMINT DEFAULT 1;
	DECLARE partName VARCHAR(50);
	IF ISNULL(createtable) THEN
		SELECT 'badargument:tablename is null or createtable is null';LEAVE loopout;END IF;
	IF LENGTH(createtable)<=0 THEN
		SELECT 'badargument:tablename is empty or createtable is empty';LEAVE loopout;END IF;
	IF parttitionnum>1024 THEN
		SELECT 'partitionnum is invalid,and parttitionnum must less than 1024';LEAVE loopout;END IF;
	
	# delete old partition 
	SELECT COUNT(*) INTO partNum FROM information_schema.partitions WHERE table_schema=SCHEMA() AND table_name='me_soe_temp';
	SELECT partition_name INTO partName FROM information_schema.partitions WHERE table_schema=SCHEMA() AND 
	table_name='me_soe_temp' ORDER BY partition_ordinal_position LIMIT 1;

	IF partNum>=1024 THEN
		ALTER TABLE base.me_soe_temp DROP PARTITION partName;END IF;
	
	
	SET @sqlcreatetable=createtable;
	SET @sqlpartition=' partition  by range(to_days(t))(';
	SET @sqlconcate='';
	SET @sqlclose=');';
	loopin:LOOP
		IF  parttitionnum<=0 THEN				 
			LEAVE loopin;END IF;
		SET @datebase=DATE_SUB(NOW(),INTERVAL parttitionnum DAY);
		SET @date=TO_DAYS(@datebase);
		SET @dateformat=DATE_FORMAT(@datebase,'%Y-%m-%d');
 		SET @sqlconcate=CONCAT(@sqlconcate,'partition partition_',@date, 
		' values less than (to_days(\'',@dateformat,'\')),');
		SET parttitionnum=parttitionnum-1;	
	END LOOP;
	SET @sqlconcate=LEFT(@sqlconcate,LENGTH(@sqlconcate)-1);		
	SET @sqlstr=CONCAT(@sqlcreatetable,@sqlpartition,@sqlconcate,@sqlclose);
	-- select @sqlstr;
	PREPARE stmt FROM @sqlstr;
	EXECUTE stmt;
 END loopout;
END
//
DELIMITER ;

# drop partition  can't use
DROP PROCEDURE IF EXISTS base.sp_DropParttion;
DELIMITER //
CREATE PROCEDURE base.sp_DropParttion(tablename VARCHAR(255))
BEGIN
loopout:BEGIN
	# get parttions detail
	# select * from information_schema.PARTITIONS where table_schema=schema() and table_name='me_soe'
	
	# chech argument is valid
 	IF ISNULL(tablename) THEN
		SELECT 'badargument:tablename is null';LEAVE loopout;END IF;
	IF LENGTH(tablename)<=0 THEN
		SELECT 'badargument:tablename is empty';LEAVE loopout;END IF	
	# delete old partition 
	SET @sqlstr=CONCAT('SELECT COUNT(*) INTO @partNum FROM information_schema.partitions WHERE table_schema=SCHEMA() AND table_name=\'',
	tablename,'\'
	;SELECT partition_name INTO @partName FROM information_schema.partitions WHERE table_schema=SCHEMA() AND 
	table_name=\'',tablename,'\' ORDER BY partition_ordinal_position LIMIT 1;
	IF @partNum>=1024 THEN
		ALTER TABLE base.',tablename,' DROP PARTITION @partName;END IF;');	
	 
	SELECT @sqlstr;
	#prepare stmt from @sqlstr;
	#execute stmt;
 END loopout;
END
//
DELIMITER ;

CALL base.sp_DropParttion('me_soe_temp');

# test base.sp_CreateParttionTable()
CALL base.sp_CreateParttionTable('CREATE TABLE cisp_platform.me_soe_temp (                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
          `SOEID` varchar(32) NOT NULL COMMENT \'事件ID\',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
          `DEV_ID` varchar(64) DEFAULT NULL COMMENT \'关联设备ID\',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
          `MEASUREPOINT_ID` varchar(64) DEFAULT NULL COMMENT \'测量点ID\',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
          `MEASURETAG` varchar(32) NOT NULL COMMENT \'量测量类型\',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
          `VALUE` text COMMENT \'值说明:JASON格式\',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
          `EVENTTYPE` decimal(2,0) NOT NULL COMMENT \'事件分类\',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
          `EVENTLEVEL` decimal(2,0) NOT NULL COMMENT \'事件等级\',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
          `EVENTDESC` text COMMENT \'事件描述\',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
          `T` datetime DEFAULT NULL COMMENT \'事件时标\',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
          `ISPROCESSED` tinyint(4) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
          `OPERATOR` varchar(32) DEFAULT NULL COMMENT \'处理人\',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
          `OPTIME` datetime DEFAULT NULL COMMENT \'处理时间\',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
          `ISRETURN` tinyint(4) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
          `RETURNTIME` datetime DEFAULT NULL COMMENT \'复归时间\',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
          `BURO` varchar(32) NOT NULL COMMENT \'所属管理单位\',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
          `SUBBURO` varchar(32) NOT NULL COMMENT \'数据所属单位\',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
          `ISSOE` decimal(1,0) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
          `ISALARM` tinyint(4) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
          `ISHOLD` decimal(1,0) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
          `LASTALARMID` varchar(32) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
          `DEV_NAME` varchar(128) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
          `SOURCE` varchar(64) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
          `MEASURENAME` varchar(128) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
          `RUNNINGNUMBER` bigint(20) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
          KEY `SOEID` (`SOEID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
          KEY `INDEX_RUNNINGNUMBER` (`RUNNINGNUMBER`) USING BTREE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
          KEY `DEV_ID` (`DEV_ID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
          KEY `T` (`T`)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT=\'SOE事件表\'',500);


SELECT * FROM information_schema.events

SELECT * FROM information_schema.partitions WHERE table_schema='cisp_platform' AND table_name='me_soe'

SELECT partition_name FROM information_schema.partitions WHERE table_schema=SCHEMA() AND table_name='me_soe' ORDER BY partition_ordinal_position 
 
SELECT COUNT(*) FROM information_schema.partitions WHERE table_schema=SCHEMA() AND table_name='me_soe'

# create store procedure add new date partition
DROP PROCEDURE IF EXISTS base.sp_CreateNewDatePartition;
DELIMITER //
CREATE PROCEDURE base.sp_CreateNewDatePartition()
BEGIN
	DECLARE partNum MEDIUMINT DEFAULT 1;
	DECLARE partName VARCHAR(30);
	# drop old partition
	SELECT COUNT(*) INTO partNum FROM information_schema.partitions WHERE table_schema='cisp_platform' AND table_name='me_soe';
	SELECT partition_name INTO partName FROM information_schema.partitions WHERE table_schema='cisp_platform' AND 
	table_name='me_soe' ORDER BY partition_ordinal_position LIMIT 1;

	IF partNum>=1024 THEN
		ALTER TABLE cisp_platform.me_soe DROP PARTITION partName;END IF;
	SET @datebase=DATE_ADD(NOW(),INTERVAL 1 DAY);
	SET @date=TO_DAYS(@datebase);
	SET @dateformat=DATE_FORMAT(@datebase,'%Y-%m-%d');
	SET @partition_name=CONCAT('partition_',@date);
	
	SET @sqlstr=CONCAT('alter table cisp_platform.me_soe add partition (partition ',@partition_name,' values less than (to_days(\'',@dateformat,'\')));');
	
	PREPARE stmt FROM @sqlstr;
	EXECUTE stmt;
END //
DELIMITER ;

ALTER TABLE cisp_platform.me_soe_temp DROP PARTITION partition_736396
CALL base.sp_CreateNewDatePartition;


# create event call base.sp_CreateNewDatePartition() every day at time 01:00:00

DROP EVENT IF EXISTS base.evnt_create_partition_everyday;
DELIMITER //
CREATE EVENT base.evnt_create_partition_everyday
ON SCHEDULE EVERY 1 DAY STARTS '2018-12-28 01:00:00' DO CALL base.sp_CreateNewDatePartition();
//
DELIMITER ;

INSERT INTO base.me_soe SELECT * FROM cisp_platform.me_soe;

SHOW PROCESSLIST

SELECT * FROM cisp_platform.me_soe INTO OUTFILE 'D:\var\mesoe.txt';


SELECT COUNT(*) FROM cisp_platform.me_soe_temp 
SELECT COUNT(*) FROM cisp_platform.me_soe

SELECT COUNT(*) FROM cisp_platform.me_soe_copy


SELECT * FROM cisp_platform.me_soe WHERE t>STR_TO_DATE('2018-12-26 20:30:00','%Y-%m-%d %H:%i:%s')

SELECT TO_DAYS('2018-12-28 20:30:00')


INSERT INTO cisp_platform.me_soe_temp SELECT * FROM cisp_platform.me_soe WHERE t>STR_TO_DATE('2018-12-26 20:30:00','%Y-%m-%d %H:%i:%s')

SHOW PROCESSLIST;

SELECT @temp=12;
SET @sss =DATE_FORMAT(DATE_SUB(NOW(),INTERVAL @temp DAY),'%Y-%m-%d');
SELECT @sss;


SELECT TO_DAYS(DATE_SUB(NOW(),INTERVAL 1 DAY)),TO_DAYS(DATE_SUB(NOW(),INTERVAL 2 DAY))







