CREATE TABLE base.me_soe_123 (
     SOEID VARCHAR (32) NOT NULL COMMENT '事件ID', DEV_ID VARCHAR (64) DEFAULT NULL COMMENT '关联设备ID', MEASUREPOINT_ID VARCHAR (64) DEFAULT NULL COMMENT '测量点ID', MEASURETAG VARCHAR (32) NOT NULL COMMENT '量测量类型', VALUE TEXT COMMENT '值说明:JASON格式', EVENTTYPE DECIMAL (2, 0) NOT NULL COMMENT '事件分类', EVENTLEVEL DECIMAL (2, 0) NOT NULL COMMENT '事件等级', EVENTDESC TEXT COMMENT '事件描述', T DATETIME NOT NULL COMMENT '事件时标', ISPROCESSED DECIMAL (1, 0) NOT NULL COMMENT '是否确认:0-未确认,1-已确认', OPERATOR VARCHAR (32) DEFAULT NULL COMMENT '处理人', OPTIME DATETIME DEFAULT NULL COMMENT '处理时间', ISRETURN DECIMAL (1, 0) NOT NULL COMMENT '是否归复:0-未复归,1-已复归', RETURNTIME DATETIME DEFAULT NULL COMMENT '复归时间', BURO VARCHAR (32) NOT NULL COMMENT '所属管理单位', SUBBURO VARCHAR (32) NOT NULL COMMENT '数据所属单位', ISSOE DECIMAL (1, 0) NOT NULL, ISALARM DECIMAL (1, 0) NOT NULL, ISHOLD DECIMAL (1, 0) NOT NULL, LASTALARMID VARCHAR (32) DEFAULT NULL, DEV_NAME VARCHAR (128) DEFAULT NULL, SOURCE VARCHAR (64) DEFAULT NULL, MEASURENAME VARCHAR (128) DEFAULT NULL, RUNNINGNUMBER BIGINT (20) DEFAULT NULL, 
     KEY DEV_ID (DEV_ID), KEY T (T)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT = 'SOE事件表' PARTITION BY RANGE (TO_DAYS(t)) (
     PARTITION ffdbfb
     VALUES
          LESS THAN 
               (TO_DAYS('2018-12-12'))
          
     );
     
     		
-- drop table base.me_soe_123		
#select TO_DAYS(DATE_SUB(NOW(),INTERVAL 1 DAY))